import { X509Certificate, createHash, createPublicKey, createVerify } from "node:crypto";

import { decodeCbor } from "./cbor.ts";
import type { CborValue } from "./cbor.ts";
import { nonceFromExtension } from "./der.ts";

/**
 * Apple App Attest verification.
 *
 * Registration proves a key was generated by the Secure Enclave of a genuine
 * device running this app. Every later request carries an assertion signed by
 * that key over the request body, with a counter that must strictly increase.
 *
 *   challenge  →  attestation  →  stored public key  →  assertions
 *
 * The Apple root certificate and the app identity are injected, so the whole
 * flow is exercised in tests against a synthetic chain. Passing those tests
 * means the protocol is implemented; it does not mean Apple has accepted a real
 * attestation. That remains a signed-device verification.
 */

/** Apple's OID for the attestation nonce extension on the credential cert. */
const NONCE_EXTENSION_OID = "1.2.840.113635.100.8.2";

const AAGUID_PRODUCTION = "appattest\0\0\0\0\0\0\0";
const AAGUID_DEVELOPMENT = "appattestdevelop";

export type AppAttestEnvironment = "development" | "production";

export class AttestationError extends Error {
  readonly reason: string;

  constructor(reason: string) {
    super(reason);
    this.name = "AttestationError";
    this.reason = reason;
  }
}

export type AttestationInput = {
  keyID: string;
  /** Base64 CBOR attestation object from `DCAppAttestService`. */
  attestation: string;
  /** The one-time challenge this attestation is bound to. */
  challenge: string;
};

export type VerifierOptions = {
  /** `<teamID>.<bundleID>`. */
  appID: string;
  environment: AppAttestEnvironment;
  /** Apple App Attest Root CA, PEM. A test root in fixtures. */
  rootCertificatePEM: string;
};

export type AttestationResult = {
  keyID: string;
  /** SPKI DER, base64. */
  publicKey: string;
  environment: AppAttestEnvironment;
  counter: number;
};

type AuthenticatorData = {
  rpIDHash: Uint8Array;
  counter: number;
  aaguid: string;
  credentialID: Uint8Array;
};

type CborMap = { [key: string]: CborValue };

function asMap(value: CborValue, field: string): CborMap {
  if (
    typeof value !== "object" ||
    value === null ||
    Array.isArray(value) ||
    value instanceof Uint8Array
  ) {
    throw new AttestationError(field);
  }
  return value;
}

function bytes(value: CborValue | undefined, field: string): Uint8Array {
  if (!(value instanceof Uint8Array)) throw new AttestationError(`${field}_missing`);
  return value;
}

function sha256(...parts: Uint8Array[]): Buffer {
  const hash = createHash("sha256");
  for (const part of parts) hash.update(part);
  return hash.digest();
}

function equal(left: Uint8Array, right: Uint8Array): boolean {
  if (left.length !== right.length) return false;
  let difference = 0;
  for (let index = 0; index < left.length; index += 1) difference |= left[index]! ^ right[index]!;
  return difference === 0;
}

/**
 * WebAuthn-style authenticator data. Apple's attested credential block follows
 * the 37-byte header; assertions carry the header only.
 */
export function parseAuthenticatorData(data: Uint8Array): AuthenticatorData {
  if (data.length < 37) throw new AttestationError("authenticator_data_truncated");
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const parsed: AuthenticatorData = {
    rpIDHash: data.subarray(0, 32),
    counter: view.getUint32(33),
    aaguid: "",
    credentialID: new Uint8Array(),
  };

  if (data.length >= 55) {
    parsed.aaguid = new TextDecoder("latin1").decode(data.subarray(37, 53));
    const credentialLength = view.getUint16(53);
    parsed.credentialID = data.subarray(55, 55 + credentialLength);
  }
  return parsed;
}

function verifyChain(chain: X509Certificate[], root: X509Certificate): void {
  if (chain.length === 0) throw new AttestationError("empty_certificate_chain");
  const full = [...chain, root];
  for (let index = 0; index < full.length - 1; index += 1) {
    if (!full[index]!.verify(full[index + 1]!.publicKey)) {
      throw new AttestationError("certificate_chain_invalid");
    }
  }
}

/**
 * The key identifier is the SHA-256 of the credential certificate's public key
 * in uncompressed point form. Checking it is what binds this attestation to the
 * key ID the client claimed.
 */
function keyIdentifier(certificate: X509Certificate): string {
  const raw = certificate.publicKey.export({ type: "spki", format: "der" });
  // The uncompressed EC point is the trailing 65 bytes of the SPKI encoding.
  const point = raw.subarray(raw.length - 65);
  return sha256(point).toString("base64");
}

export function verifyAttestation(
  input: AttestationInput,
  options: VerifierOptions,
): AttestationResult {
  let decoded: CborValue;
  try {
    decoded = decodeCbor(Buffer.from(input.attestation, "base64"));
  } catch {
    throw new AttestationError("attestation_not_cbor");
  }
  const attestation = asMap(decoded, "attestation_malformed");

  if (attestation.fmt !== "apple-appattest") throw new AttestationError("unexpected_format");

  const statement = asMap(
    attestation.attStmt ?? new Uint8Array(),
    "attestation_statement_missing",
  );
  const chainValue = statement.x5c;
  if (!Array.isArray(chainValue) || chainValue.length === 0) {
    throw new AttestationError("certificate_chain_missing");
  }

  const chain = chainValue.map((entry, index) => {
    try {
      return new X509Certificate(Buffer.from(bytes(entry, `x5c_${index}`)));
    } catch {
      throw new AttestationError("certificate_unparseable");
    }
  });
  const credentialCertificate = chain[0]!;

  verifyChain(chain, new X509Certificate(options.rootCertificatePEM));

  const authData = bytes(attestation.authData, "authData");

  // 2. nonce = SHA256(authData || SHA256(challenge))
  const expectedNonce = sha256(authData, sha256(Buffer.from(input.challenge, "utf8")));

  const extension = extensionValue(credentialCertificate, NONCE_EXTENSION_OID);
  if (!extension) throw new AttestationError("nonce_extension_missing");
  let presentedNonce: Uint8Array;
  try {
    presentedNonce = nonceFromExtension(extension);
  } catch {
    throw new AttestationError("nonce_extension_malformed");
  }
  if (!equal(presentedNonce, expectedNonce)) throw new AttestationError("challenge_mismatch");

  // 4. The claimed key ID must be this certificate's key.
  const derivedKeyID = keyIdentifier(credentialCertificate);
  if (derivedKeyID !== input.keyID) throw new AttestationError("key_id_mismatch");

  // 5. The app identity, environment, counter, and credential ID.
  const parsed = parseAuthenticatorData(authData);
  if (!equal(parsed.rpIDHash, sha256(Buffer.from(options.appID, "utf8")))) {
    throw new AttestationError("app_id_mismatch");
  }
  const expectedAaguid =
    options.environment === "production" ? AAGUID_PRODUCTION : AAGUID_DEVELOPMENT;
  if (parsed.aaguid !== expectedAaguid) throw new AttestationError("environment_mismatch");
  if (parsed.counter !== 0) throw new AttestationError("unexpected_attestation_counter");
  if (!equal(parsed.credentialID, Buffer.from(input.keyID, "base64"))) {
    throw new AttestationError("credential_id_mismatch");
  }

  return {
    keyID: input.keyID,
    publicKey: credentialCertificate.publicKey
      .export({ type: "spki", format: "der" })
      .toString("base64"),
    environment: options.environment,
    counter: parsed.counter,
  };
}

export type AssertionInput = {
  /** Base64 CBOR assertion from `DCAppAttestService`. */
  assertion: string;
  /** Exactly the bytes the client signed — the serialized request body. */
  clientData: Uint8Array;
  /** SPKI DER, base64, from the stored key record. */
  publicKey: string;
};

export type AssertionResult = { counter: number };

export function verifyAssertion(input: AssertionInput, options: VerifierOptions): AssertionResult {
  let decoded: CborValue;
  try {
    decoded = decodeCbor(Buffer.from(input.assertion, "base64"));
  } catch {
    throw new AttestationError("assertion_not_cbor");
  }
  const assertion = asMap(decoded, "assertion_malformed");

  const signature = bytes(assertion.signature, "signature");
  const authenticatorData = bytes(assertion.authenticatorData, "authenticatorData");

  const parsed = parseAuthenticatorData(authenticatorData);
  if (!equal(parsed.rpIDHash, sha256(Buffer.from(options.appID, "utf8")))) {
    throw new AttestationError("app_id_mismatch");
  }

  // The signed payload binds the request body to this assertion, so a valid
  // assertion cannot be lifted onto a different request.
  const nonce = sha256(authenticatorData, sha256(input.clientData));

  const verifier = createVerify("SHA256");
  verifier.update(nonce);
  verifier.end();
  const key = createPublicKey({
    key: Buffer.from(input.publicKey, "base64"),
    format: "der",
    type: "spki",
  });
  if (!verifier.verify(key, Buffer.from(signature))) {
    throw new AttestationError("assertion_signature_invalid");
  }

  return { counter: parsed.counter };
}

function extensionValue(certificate: X509Certificate, oid: string): Uint8Array | undefined {
  // node:crypto exposes no extension accessor, so the DER is scanned for the
  // encoded OID and the OCTET STRING that follows it.
  const raw = new Uint8Array(certificate.raw);
  const encodedOID = encodeOID(oid);
  outer: for (let index = 0; index + encodedOID.length < raw.length; index += 1) {
    for (let offset = 0; offset < encodedOID.length; offset += 1) {
      if (raw[index + offset] !== encodedOID[offset]) continue outer;
    }
    let cursor = index + encodedOID.length;
    // An optional BOOLEAN critical flag may sit between the OID and the value.
    if (raw[cursor] === 0x01) cursor += 3;
    if (raw[cursor] !== 0x04) continue;
    const { node } = readOctetString(raw, cursor);
    return node;
  }
  return undefined;
}

function readOctetString(bytes: Uint8Array, offset: number): { node: Uint8Array } {
  let cursor = offset + 1;
  const first = bytes[cursor]!;
  cursor += 1;
  let length = first;
  if (first >= 0x80) {
    const count = first & 0x7f;
    length = 0;
    for (let index = 0; index < count; index += 1) {
      length = (length << 8) | bytes[cursor]!;
      cursor += 1;
    }
  }
  return { node: bytes.subarray(cursor, cursor + length) };
}

export function encodeOID(oid: string): Uint8Array {
  const parts = oid.split(".").map(Number);
  const body: number[] = [40 * parts[0]! + parts[1]!];
  for (const part of parts.slice(2)) {
    const chunks: number[] = [];
    let value = part;
    do {
      chunks.unshift(value & 0x7f);
      value >>= 7;
    } while (value > 0);
    for (let index = 0; index < chunks.length - 1; index += 1) chunks[index]! |= 0x80;
    body.push(...chunks);
  }
  return Uint8Array.from([0x06, body.length, ...body]);
}
