#!/usr/bin/env python3
"""Generate the API's runtime artifacts from the shared source of truth.

`shared/contracts/intelligence-api.yaml` stays the human-facing spec. This
emits what the deployed functions actually load, into `api/generated/`, so
production never reaches sideways into `../shared` at runtime:

  schemas/api.schema.json                  client <-> PackWise API. Full JSON Schema.
  schemas/model-output/<capability>.json   PackWise API <-> model. One strict schema
                                           per capability, restricted to the OpenAI
                                           Structured Outputs subset: every property
                                           required, additionalProperties false, no
                                           numeric/string constraint keywords,
                                           optionality as a nullable type.
  vocab/*.json                             closed vocabularies: canonical item IDs,
                                           context chips, activities, reason codes.
  manifest.json                            schemaVersion and a content buildHash.

Closed vocabularies come from `shared/rules/`, so the model physically cannot
return a chip, activity, or reason code the app does not know.

Run `python3 scripts/build_intelligence_schemas.py`; `validate_shared.py` fails
if the checked-in artifacts no longer match.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SHARED = ROOT / "shared"
OUT_DIR = ROOT / "api" / "generated"

SCHEMA_VERSION = "2026-08-29"

CAPABILITY_SCHEMAS = {
    "interpret": "TripInterpretation",
    "gaps": "PackingGaps",
    "optimize": "PackingOptimizations",
}

SUGGESTION_ACTIONS = ["recommend", "remove_candidate", "quantity_change"]

# Mirrors RecommendationSignal in ios/PackWise/Domain/TripTypes.swift.
RECOMMENDATION_SIGNALS = [
    "weather",
    "duration",
    "activity",
    "tripType",
    "destination",
    "baseEssential",
    "userPreference",
    "history",
    "gptReasoning",
    "party",
]

TRIP_TYPES = [
    "vacation",
    "cityBreak",
    "beach",
    "business",
    "outdoor",
    "roadTrip",
    "weddingEvent",
    "skiSnow",
    "festival",
    "visitingFamily",
    "other",
]

BAG_TYPES = ["personalItem", "carryOn", "checked", "backpack", "roadTripLuggage", "notSure"]
PACKING_STYLES = ["light", "balanced", "prepared"]
TRANSPORTATION = ["flight", "drive", "train", "cruise", "other", "unknown"]
LAUNDRY_ACCESS = ["none", "possible", "planned"]

MAX_NOTE_LENGTH = 2000
MAX_ITEMS = 400


def load(path: Path):
    return json.loads(path.read_text())


def placeholders(template: str) -> list[str]:
    return sorted(set(re.findall(r"\{(\w+)\}", template)))


def reason_arguments(reasons: dict[str, str], prefix: str) -> dict[str, list[str]]:
    return {code: placeholders(body) for code, body in sorted(reasons.items()) if code.startswith(prefix)}


def vocabularies() -> dict[str, list[str]]:
    base = load(SHARED / "rules" / "base.json")
    activities = load(SHARED / "rules" / "activity-rules.json")["activities"]
    reasons = load(SHARED / "rules" / "reasons.json")["templates"]
    return {
        "contextChips": sorted(base["context_chips"]),
        "activities": sorted(activities),
        "gapReasonCodes": sorted(k for k in reasons if k.startswith("context.gap_")),
        "optimizeReasonCodes": sorted(k for k in reasons if k.startswith("context.optimize_")),
        "gapArguments": reason_arguments(reasons, "context.gap_"),
        "optimizeArguments": reason_arguments(reasons, "context.optimize_"),
    }


def api_schema(vocab: dict[str, list[str]]) -> dict:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://packwise.app/schemas/intelligence/api.schema.json",
        "title": "PackWise Intelligence API",
        "description": "Generated by scripts/build_intelligence_schemas.py. Do not edit by hand.",
        "$defs": {
            "APIError": {
                "type": "object",
                "required": ["error", "requestID"],
                "properties": {
                    "error": {"type": "string"},
                    "message": {"type": "string"},
                    "requestID": {"type": "string"},
                },
            },
            "IntelligenceMeta": {
                "type": "object",
                "required": ["requestID", "generatedAt", "promptVersion", "schemaVersion"],
                "properties": {
                    "requestID": {"type": "string"},
                    "generatedAt": {"type": "string"},
                    "model": {"type": "string"},
                    "promptVersion": {"type": "string"},
                    "schemaVersion": {"type": "string"},
                    "cached": {"type": "boolean"},
                },
            },
            "DestinationDTO": {
                "type": "object",
                "required": ["displayName", "countryCode"],
                "properties": {
                    "displayName": {"type": "string", "minLength": 1},
                    "countryCode": {"type": "string", "minLength": 2, "maxLength": 2},
                    "latitude": {"type": "number", "minimum": -90, "maximum": 90},
                    "longitude": {"type": "number", "minimum": -180, "maximum": 180},
                },
            },
            "TripContextDTO": {
                "type": "object",
                "required": [
                    "destination",
                    "startDate",
                    "endDate",
                    "tripType",
                    "activities",
                    "bagType",
                    "packingStyle",
                ],
                "properties": {
                    "destination": {"$ref": "#/$defs/DestinationDTO"},
                    "startDate": {"type": "string", "format": "date"},
                    "endDate": {"type": "string", "format": "date"},
                    "durationDays": {"type": "integer", "minimum": 1},
                    "tripType": {"enum": TRIP_TYPES},
                    "activities": {"type": "array", "items": {"enum": vocab["activities"]}},
                    "contextChips": {"type": "array", "items": {"enum": vocab["contextChips"]}},
                    "bagType": {"enum": BAG_TYPES},
                    "packingStyle": {"enum": PACKING_STYLES},
                    "transportation": {"enum": TRANSPORTATION},
                    "laundryAccess": {"enum": LAUNDRY_ACCESS},
                    "travelerCount": {"type": "integer", "minimum": 1},
                    "userNotes": {"type": "string", "maxLength": MAX_NOTE_LENGTH},
                    "weatherSummary": {"type": "string", "maxLength": 600},
                    "currentItemIDs": {
                        "type": "array",
                        "maxItems": MAX_ITEMS,
                        "items": {"type": "string"},
                    },
                },
            },
            "PackingItemDTO": {
                "type": "object",
                "required": ["displayName"],
                "properties": {
                    "canonicalItemID": {"type": "string"},
                    "displayName": {"type": "string", "minLength": 1},
                    "quantity": {"type": "integer", "minimum": 0},
                    "category": {"type": "string"},
                },
            },
            "PackingSuggestionDTO": {
                "type": "object",
                "description": (
                    "reasonCode plus reasonArguments is the durable identifier PackWise "
                    "renders from a localized template. reason is fallback prose."
                ),
                "required": ["canonicalItemID", "action", "reasonCode"],
                "properties": {
                    "canonicalItemID": {"type": "string", "minLength": 1},
                    "action": {"enum": SUGGESTION_ACTIONS},
                    "confidence": {"type": "number", "minimum": 0, "maximum": 1},
                    "signals": {"type": "array", "items": {"enum": RECOMMENDATION_SIGNALS}},
                    "reason": {"type": "string"},
                    "reasonCode": {"type": "string", "minLength": 1},
                    "reasonArguments": {
                        "type": "object",
                        "additionalProperties": {"type": "string"},
                    },
                },
            },
            "PackingOptimizationDTO": {
                "type": "object",
                "required": ["canonicalItemID", "reasonCode"],
                "properties": {
                    "canonicalItemID": {"type": "string", "minLength": 1},
                    "reason": {"type": "string"},
                    "reasonCode": {"type": "string", "minLength": 1},
                    "reasonArguments": {
                        "type": "object",
                        "additionalProperties": {"type": "string"},
                    },
                    "suggestedQuantity": {"type": "integer", "minimum": 0},
                    "confidence": {"type": "number", "minimum": 0, "maximum": 1},
                },
            },
            "InterpretTripRequest": {
                "type": "object",
                "required": ["note", "context", "safetyIdentifier"],
                "properties": {
                    "note": {"type": "string", "minLength": 1, "maxLength": MAX_NOTE_LENGTH},
                    "context": {"$ref": "#/$defs/TripContextDTO"},
                    "safetyIdentifier": {"type": "string", "minLength": 8, "maxLength": 128},
                },
            },
            "InterpretTripResponse": {
                "type": "object",
                "required": ["meta", "inferredActivities", "inferredChips"],
                "properties": {
                    "meta": {"$ref": "#/$defs/IntelligenceMeta"},
                    "inferredActivities": {"type": "array", "items": {"enum": vocab["activities"]}},
                    "inferredChips": {"type": "array", "items": {"enum": vocab["contextChips"]}},
                    "noteSummary": {"type": "string"},
                },
            },
            "PackingGapsRequest": {
                "type": "object",
                "required": ["context", "items", "safetyIdentifier"],
                "properties": {
                    "context": {"$ref": "#/$defs/TripContextDTO"},
                    "items": {
                        "type": "array",
                        "maxItems": MAX_ITEMS,
                        "items": {"$ref": "#/$defs/PackingItemDTO"},
                    },
                    "safetyIdentifier": {"type": "string", "minLength": 8, "maxLength": 128},
                },
            },
            "PackingGapResponse": {
                "type": "object",
                "required": ["meta", "suggestions"],
                "properties": {
                    "meta": {"$ref": "#/$defs/IntelligenceMeta"},
                    "suggestions": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/PackingSuggestionDTO"},
                    },
                },
            },
            "PackingOptimizeRequest": {
                "type": "object",
                "required": ["context", "items", "safetyIdentifier"],
                "properties": {
                    "context": {"$ref": "#/$defs/TripContextDTO"},
                    "items": {
                        "type": "array",
                        "maxItems": MAX_ITEMS,
                        "items": {"$ref": "#/$defs/PackingItemDTO"},
                    },
                    "safetyIdentifier": {"type": "string", "minLength": 8, "maxLength": 128},
                },
            },
            "PackingOptimizationResponse": {
                "type": "object",
                "required": ["meta", "optimizations"],
                "properties": {
                    "meta": {"$ref": "#/$defs/IntelligenceMeta"},
                    "optimizations": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/PackingOptimizationDTO"},
                    },
                },
            },
        },
    }


def nullable(kind: str) -> dict:
    return {"type": [kind, "null"]}


def reason_arguments_schema(names: list[str]) -> dict:
    """Structured Outputs forbids free-form maps, so arguments travel as pairs.

    The names are closed: a reason code renders a localized template, and an
    argument the template does not use cannot be substituted into it.
    """
    return {
        "type": "array",
        "items": {
            "type": "object",
            "additionalProperties": False,
            "required": ["name", "value"],
            "properties": {
                "name": {"enum": names} if names else {"type": "string"},
                "value": {"type": "string"},
            },
        },
    }


def model_output_schema(vocab: dict[str, list[str]]) -> dict:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://packwise.app/schemas/intelligence/model-output.schema.json",
        "title": "PackWise model output",
        "description": (
            "Generated by scripts/build_intelligence_schemas.py. Do not edit by hand. "
            "Restricted to the Structured Outputs strict subset."
        ),
        "$defs": {
            "TripInterpretation": {
                "type": "object",
                "additionalProperties": False,
                "required": ["inferredActivities", "inferredChips", "noteSummary"],
                "properties": {
                    "inferredActivities": {"type": "array", "items": {"enum": vocab["activities"]}},
                    "inferredChips": {"type": "array", "items": {"enum": vocab["contextChips"]}},
                    "noteSummary": nullable("string"),
                },
            },
            "PackingGaps": {
                "type": "object",
                "additionalProperties": False,
                "required": ["suggestions"],
                "properties": {
                    "suggestions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": [
                                "canonicalItemID",
                                "reasonCode",
                                "reasonArguments",
                                "reason",
                                "confidence",
                                "signals",
                            ],
                            "properties": {
                                "canonicalItemID": {"type": "string"},
                                "reasonCode": {"enum": vocab["gapReasonCodes"]},
                                "reasonArguments": reason_arguments_schema(
                                    sorted({n for names in vocab["gapArguments"].values() for n in names})
                                ),
                                "reason": nullable("string"),
                                "confidence": {"type": "number"},
                                "signals": {
                                    "type": "array",
                                    "items": {"enum": RECOMMENDATION_SIGNALS},
                                },
                            },
                        },
                    }
                },
            },
            "PackingOptimizations": {
                "type": "object",
                "additionalProperties": False,
                "required": ["optimizations"],
                "properties": {
                    "optimizations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": [
                                "canonicalItemID",
                                "reasonCode",
                                "reasonArguments",
                                "reason",
                                "suggestedQuantity",
                                "confidence",
                            ],
                            "properties": {
                                "canonicalItemID": {"type": "string"},
                                "reasonCode": {"enum": vocab["optimizeReasonCodes"]},
                                "reasonArguments": reason_arguments_schema(
                                    sorted({n for names in vocab["optimizeArguments"].values() for n in names})
                                ),
                                "reason": nullable("string"),
                                "suggestedQuantity": nullable("integer"),
                                "confidence": {"type": "number"},
                            },
                        },
                    }
                },
            },
        },
    }


def canonical_items() -> list[str]:
    ids: list[str] = []
    for path in sorted((SHARED / "catalog").glob("*.json")):
        ids.extend(item["id"] for item in load(path)["items"])
    return sorted(ids)


def render() -> dict[Path, str]:
    """Only the runtime artifacts the API needs, each self-contained."""
    vocab = vocabularies()
    files: dict[Path, str] = {}

    def write(relative: str, payload) -> None:
        files[OUT_DIR / relative] = json.dumps(payload, indent=2) + "\n"

    write("schemas/api.schema.json", api_schema(vocab))

    # One strict schema per capability: the Responses API takes a single schema
    # per request, so the combined document is split rather than $ref'd.
    combined = model_output_schema(vocab)
    for capability, definition in CAPABILITY_SCHEMAS.items():
        schema = dict(combined["$defs"][definition])
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        schema["title"] = definition
        write(f"schemas/model-output/{capability}.schema.json", schema)

    write("vocab/canonical-items.json", {"items": canonical_items()})
    write("vocab/context-chips.json", {"chips": vocab["contextChips"]})
    write("vocab/activities.json", {"activities": vocab["activities"]})
    reasons = load(SHARED / "rules" / "reasons.json")["templates"]
    write(
        "vocab/reason-codes.json",
        {
            "all": sorted(reasons),
            "gaps": vocab["gapReasonCodes"],
            "optimize": vocab["optimizeReasonCodes"],
            "arguments": {code: placeholders(body) for code, body in sorted(reasons.items())},
        },
    )

    # A content hash, not a timestamp, so the artifact is reproducible and
    # --check stays meaningful.
    digest = hashlib.sha256()
    for path in sorted(files):
        digest.update(path.name.encode())
        digest.update(files[path].encode())

    files[OUT_DIR / "manifest.json"] = (
        json.dumps(
            {
                "schemaVersion": SCHEMA_VERSION,
                "buildHash": digest.hexdigest()[:16],
                "capabilities": {
                    capability: {
                        "schema": f"schemas/model-output/{capability}.schema.json",
                        "definition": definition,
                    }
                    for capability, definition in CAPABILITY_SCHEMAS.items()
                },
            },
            indent=2,
        )
        + "\n"
    )
    return files


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for path, body in render().items():
        if check:
            if not path.exists() or path.read_text() != body:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
    if stale:
        print("stale generated artifacts: " + ", ".join(stale), file=sys.stderr)
        print("run python3 scripts/build_intelligence_schemas.py", file=sys.stderr)
        return 1
    if not check:
        print(f"OK: wrote {len(render())} generated files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
